name: Code Coverage

on: [pull_request]

jobs:
    coverage:
        runs-on: macos-11

        steps:
            - name: check out github repository
              uses: actions/checkout@v2

            - name: setup ssh-agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "14.18.0"

            - name: Install dependencies
              run: npm ci && npm run load-contracts

            - name: Coverage
              run: npm run build && node --max-old-space-size=12192 `which npm` run coverage

            - name: Edit lcov.info
              run: cat coverage/lcov.info | sed '/.*\/balancer-core-v2\/.*/,/TN:/d' | sed '/.*\/test\/.*/,/TN:/d' > coverage/tmp.info && mv coverage/tmp.info coverage/lcov.info

            - name: Coveralls
              uses: coverallsapp/github-action@v1.1.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
