name: Code Coverage

on: [pull_request]

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: check out github repository
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "13.x"

            - name: Install dependencies
              run: npm ci && npm run load-contracts

            - name: Coverage
              run: npm run build && npm run coverage

            - name: Edit lcov.info
              run: cat coverage/lcov.info | sed '/.*\/balancer-core-v2\/.*/,/TN:/d' | sed '/.*\/test\/.*/,/TN:/d' > coverage/tmp.info && mv coverage/tmp.info coverage/lcov.info

            - name: Coveralls
              uses: coverallsapp/github-action@v1.1.2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
